In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def conv(input_plane, kernel):
    kernel_size = kernel.shape[0]
    input_plane_size = input_plane.shape[0]
    total_move = input_plane_size - kernel_size + 1
    feature_map_before_activation = np.zeros((total_move, total_move))
    for i in range(total_move):
        for j in range(total_move):
            sub_input_plane = input_plane[i:i + total_move, j:j + total_move]
            feature_map_before_activation[i, j] = np.sum(np.multiply(sub_input_plane, kernel))
    return feature_map_before_activation

In [3]:
def relu(feature_map_before_activation):
    temp_matrix = (feature_map_before_activation > 0).astype(np.float64)
    feature_map = np.abs(np.multiply(feature_map_before_activation, temp_matrix))
    return feature_map

In [4]:
def create_data():
    input_plane_1 = np.array([
        [6., 0., -4., 0., 1.],
        [4., 4., 0., 2., 1.],
        [3., -7., 1., 4., 2.],
        [-2., 2., 1., -4., 2.],
        [5., 1., 2., 4., -1.]
    ])
    input_plane_2 = np.array([
        [3., 1., -4., 0., -1.],
        [3., 0., 3., 4., -1.],
        [3., 7., -2, -2, 2.],
        [-5., -2., 2., 0., -2],
        [2., 1., -1., 1., 2.]
    ])
    kernel_1 = np.array([
        [3., -1, 2.],
        [-2., 1., -3.],
        [-2., 0., 3.]
    ])
    kernel_2 = np.array([
        [0., -1., 0.],
        [-1., 6., -1.],
        [0., -1., 0.]
    ])
    return input_plane_1, input_plane_2, kernel_1, kernel_2

In [5]:
input_plane_1, input_plane_2, kernel_1, kernel_2 = create_data()
sub_feature_map_1_before_activation = conv(input_plane_1, kernel_1)
print('Sub Feature Map 1 before activation: \n{}\n'.format(sub_feature_map_1_before_activation))
sub_feature_map_2_before_activation = conv(input_plane_2, kernel_2)
print('Sub Feature Map 2 before activation: \n{}\n'.format(sub_feature_map_2_before_activation))
feature_map_before_activation = sub_feature_map_1_before_activation + sub_feature_map_2_before_activation
print('Feature Map before activation: \n{}\n'.format(feature_map_before_activation))
feature_map = relu(feature_map_before_activation)
print('Feature Map: \n{}\n'.format(feature_map))

Sub Feature Map 1 before activation: 
[[  3.  16.  -7.]
 [ -1.   3.   0.]
 [ 17.   5. -16.]]

Sub Feature Map 2 before activation: 
[[-14.  20.  24.]
 [ 43. -22. -16.]
 [-17.  17.   1.]]

Feature Map before activation: 
[[-11.  36.  17.]
 [ 42. -19. -16.]
 [  0.  22. -15.]]

Feature Map: 
[[ 0. 36. 17.]
 [42.  0.  0.]
 [ 0. 22.  0.]]

