In [1]:
import numpy as np

In [2]:
def zero_interpolation(A):
    length = A.shape[0] + A.shape[0] - 1
    new_A = np.zeros((length, length), dtype=np.float32)
    i_A = j_A = 0
    for i in range(length):
        for j in range(length):
            if (i + 1) % 2 == 1 and (j + 1) % 2 == 1:
                new_A[i, j] = A[i_A, j_A]
                j_A += 1
                if j_A % A.shape[0] == 0:
                    j_A = 0
                    i_A += 1
    return new_A

In [3]:
def conv(A, K):
    length = A.shape[0] - K.shape[0] + 1
    kernel_size = K.shape[0]
    F = np.zeros((length, length), dtype=np.float32)
    for i in range(length):
        for j in range(length):
            F[i, j] = np.sum(np.multiply(A[i:i + kernel_size, j: j + kernel_size], K))
    return F

In [4]:
def subpixel_convolution(A, K):
    A = zero_interpolation(A)
    pad_size = K.shape[0] - 1
    A = np.pad(A, (pad_size, pad_size), 'constant', constant_values=0)
    A = conv(A, K)
    return A

In [5]:
def ReLU(A):
    return np.abs(np.multiply(A, (A >= 0.).astype(np.float32)))

In [6]:
A = np.array([
    [6, 0, -4, 0, 1],
    [4, 4, 0, 2, 1],
    [3, -7, 1, 4, 2],
    [-2, 2, 1, -4, 2],
    [5, 1, 2, 4, -1]
], dtype=np.float32)
K = np.array([
    [3, -1, 2],
    [-2, 1, -3],
    [-2, 0, 3]
], dtype=np.float32)

In [7]:
A = subpixel_convolution(A, K)
A = ReLU(A)
print(A)

[[18.  0.  0.  0.  0.  0.  8.  0.  3.  0.  0.]
 [ 0.  6.  0.  0. 12.  0.  8.  0.  0.  1.  0.]
 [24.  0. 22.  0.  0.  4.  0.  0.  1.  0.  1.]
 [ 0.  4.  0.  4.  0.  0.  0.  2.  0.  1.  0.]
 [17.  0.  0.  0. 29.  0. 14.  0.  6.  0.  0.]
 [ 0.  3. 15.  0. 11.  1.  0.  4.  0.  2.  0.]
 [ 0.  0.  5.  7.  0.  0.  0.  0. 30.  0.  2.]
 [ 6.  0.  0.  2.  0.  1. 10.  0.  2.  2.  0.]
 [11.  2.  0.  0. 12.  0.  3.  4.  0.  0.  8.]
 [ 0.  5.  0.  1.  0.  2.  0.  4.  0.  0.  2.]
 [10.  0. 17.  0.  7.  0. 14.  0. 10.  1.  0.]]
